version: "3.9"

services:
  api:
    build: .
    ports:
      - 80:80
    environment:
      - DB_USER=flask_app
      - DB_PASSWORD=flask_app_password
      - DB_NAME=flask_app
      - DB_HOST=pg
    depends_on:
      - pg
  pg:
    image: postgres
    environment:
      - POSTGRES_USER=flask_app
      - POSTGRES_PASSWORD=flask_app_password
      - POSTGRES_DB=flask_app
