version: "3.9"

services:
  api:
    image: pestich/skypro_app_2:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    ports:
      - 80:80
    environment:
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_HOST=pg
    depends_on:
      - pg
  pg:
    image: postgres:latest
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME

