version: "3.9"

services:
  api:
    build: .
    ports:
      - 80:80
    environment:
      - DB_USER=flask_app
      - DB_PASSWORD=12345678
      - DB_NAME=flask_app
      - DB_HOST=db
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_USER=flask_app
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=flask_app
