name: Build and deploy
on: [push]
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: docker build
        run: docker build -t pestich/skypro_app_2:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
      - name: docker push
        run: docker push pestich/skypro_app_2:$GITHUB_REF_NAME-$GITHUB_RUN_ID